import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: 1,
    name: "Limpeza Doméstica",
    slug: "limpeza-domestica",
    icon: "Home",
    shortDescription: "Limpeza completa e profissional para a sua casa, garantindo um lar impecável e acolhedor.",
    fullDescription: "O nosso serviço de limpeza doméstica abrange todas as divisões da sua casa. Utilizamos produtos de alta qualidade e técnicas profissionais para garantir uma higienização profunda e duradoura. A nossa equipa é treinada para prestar atenção a cada detalhe, deixando a sua casa com um brilho esplêndido.",
    features: ["Limpeza de pó de todas as divisões", "Desinfeção de todas as superfícies", "Aspiração e lavagem de pavimentos", "Limpeza completa de casas de banho", "Limpeza de cozinha e eletrodomésticos", "Produtos ecológicos e profissionais"],
    image: "/images/services/limpeza-domestica.webp",
  },
  {
    id: 2,
    name: "Limpeza Comercial",
    slug: "limpeza-comercial",
    icon: "Building2",
    shortDescription: "Soluções de limpeza para escritórios, lojas e espaços comerciais.",
    fullDescription: "Oferecemos serviços de limpeza comercial adaptados às necessidades do seu negócio. Sejam escritórios, lojas ou consultórios, a nossa equipa assegura que o seu espaço está sempre limpo e pronto para receber clientes.",
    features: ["Limpeza de escritórios e áreas de trabalho", "Higienização de casas de banho comuns", "Limpeza de áreas de receção", "Reposição de consumíveis", "Horários flexíveis", "Contratos personalizados"],
    image: "/images/services/limpeza-comercial.webp",
  },
  {
    id: 3,
    name: "Higienização de Sofás",
    slug: "higienizacao-sofas",
    icon: "Sofa",
    shortDescription: "Limpeza profunda de sofás e estofados, eliminando ácaros e manchas.",
    fullDescription: "Os sofás acumulam pó, ácaros e manchas ao longo do tempo. O nosso serviço utiliza equipamentos de extração e produtos específicos para limpar em profundidade, eliminando odores e devolvendo o aspeto original.",
    features: ["Pulverização com produto desinfetante", "Escovagem profissional", "Lavagem profunda com extração", "Remoção de manchas específicas", "Eliminação de ácaros e bactérias", "Secagem rápida"],
    image: "/images/services/higienizacao-sofas.webp",
  },
  {
    id: 4,
    name: "Limpeza de Condomínios",
    slug: "limpeza-condominios",
    icon: "Building",
    shortDescription: "Manutenção e limpeza regular de espaços comuns em condomínios.",
    fullDescription: "Mantemos as áreas comuns do seu condomínio sempre limpas e apresentáveis. Desde a entrada às escadas, elevadores e garagens, garantimos a limpeza regular de todos os espaços partilhados.",
    features: ["Limpeza de halls e corredores", "Lavagem de escadas", "Limpeza de elevadores", "Higienização de garagens", "Manutenção de espaços exteriores", "Planos periódicos flexíveis"],
    image: "/images/services/limpeza-condominios.webp",
  },
  {
    id: 5,
    name: "Limpeza Pós Obra",
    slug: "limpeza-pos-obra",
    icon: "HardHat",
    shortDescription: "Remoção completa de resíduos de construção após obras ou remodelações.",
    fullDescription: "Após uma obra, o espaço fica repleto de pó, cimento e resíduos. A nossa equipa remove todos os vestígios da construção, limpa superfícies, vidros e pavimentos, deixando o espaço pronto a habitar.",
    features: ["Remoção de pó e resíduos", "Limpeza de cimento e argamassa", "Lavagem de pavimentos e azulejos", "Limpeza de vidros e caixilharias", "Desinfeção completa", "Remoção de etiquetas e cola"],
    image: "/images/services/limpeza-pos-obra.webp",
  },
  {
    id: 6,
    name: "Limpeza de Vidros e Janelas",
    slug: "limpeza-vidros-janelas",
    icon: "PanelTop",
    shortDescription: "Limpeza profissional de vidros, janelas e estores para luminosidade perfeita.",
    fullDescription: "Vidros limpos fazem toda a diferença na luminosidade de qualquer espaço. O nosso serviço inclui limpeza interior e exterior de janelas e higienização de estores, sem riscos e sem marcas.",
    features: ["Limpeza interior e exterior de vidros", "Lavagem de caixilharias", "Higienização de estores", "Remoção de calcário e poluição", "Técnicas sem riscos", "Acesso a janelas em altura"],
    image: "/images/services/limpeza-vidros.webp",
  },
  {
    id: 7,
    name: "Limpeza de Bolor e Humidade",
    slug: "limpeza-bolor-humidade",
    icon: "Droplets",
    shortDescription: "Tratamento e remoção de bolor e manchas de humidade.",
    fullDescription: "O bolor e a humidade afetam a saúde respiratória e a integridade das superfícies. O nosso serviço inclui remoção profissional, tratamento antifúngico e prevenção do reaparecimento.",
    features: ["Diagnóstico da extensão", "Remoção completa de bolor", "Tratamento anti-fúngico", "Aplicação de proteção preventiva", "Aconselhamento sobre ventilação", "Tratamento de paredes e tetos"],
    image: "/images/services/limpeza-bolor.webp",
  },
  {
    id: 8,
    name: "Higienização de Colchões",
    slug: "higienizacao-colchoes",
    icon: "Bed",
    shortDescription: "Colchões higienizados para noites tranquilas, eliminando ácaros e alérgenos.",
    fullDescription: "O nosso serviço utiliza aspiração profissional, luz ultravioleta e produtos específicos para eliminar ácaros, bactérias e alérgenos do seu colchão. Recomendado para alérgicos e famílias com crianças.",
    features: ["Aspiração de alta potência", "Tratamento com luz UV", "Eliminação de ácaros", "Remoção de manchas e odores", "Desinfetante antibacteriano", "Secagem rápida"],
    image: "/images/services/higienizacao-colchoes.webp",
  },
  {
    id: 9,
    name: "Higienização de Tapetes",
    slug: "higienizacao-tapetes",
    icon: "Layers",
    shortDescription: "Lavagem e higienização profissional de tapetes, devolvendo cor e frescura.",
    fullDescription: "Tratamos todos os tipos de tapetes, desde os mais delicados aos mais resistentes, com aspiração profunda, lavagem com extração e desinfeção completa.",
    features: ["Aspiração profunda de fibras", "Lavagem com extração", "Remoção de manchas persistentes", "Desinfeção e eliminação de odores", "Tratamento adequado a cada fibra", "Recolha e entrega ao domicílio"],
    image: "/images/services/higienizacao-tapetes.webp",
  },
];
